# Generated by Django 2.2.2 on 2019-07-09 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='restaurant name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('country', models.CharField(blank=True, max_length=200, verbose_name='restaurant country')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='restaurant city')),
                ('zip', models.CharField(blank=True, max_length=200, verbose_name='restaurant zip')),
                ('openingHours', models.CharField(blank=True, max_length=200, verbose_name='restaurant opening hours')),
                ('priceLevel', models.CharField(blank=True, max_length=200, verbose_name='restaurant price level')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='Your comment here...', max_length=1000, null=True, verbose_name='my comment content')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant', verbose_name='restaurant to comment on')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
