# Generated by Django 2.2.2 on 2019-07-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_time',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='zip',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='restaurant address'),
        ),
    ]
