name: app
dependencies:
  - python=3.6
  - psycopg2=2.7
  - pip:
      - django==2.2.2
      - flake8==3.7.7
      - djangorestframework==3.9.4
      - djangorestframework_simplejwt==4.3.0
      - Q==2.6
      - gunicorn==19.9.0