version: "3"
services:
  app:
    image: registry.gitlab.propulsion-home.ch/raquel/gunicorn_in_docker:latest
    command: gunicorn -w 4 -b 0.0.0.0:8000 --reload app:app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
