"""empty message

Revision ID: 505d9968a3a7
Revises: 5b9c7e3ec553
Create Date: 2018-03-15 14:58:05.672466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505d9968a3a7'
down_revision = '5b9c7e3ec553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo_item_tags',
    sa.Column('id', sa.Boolean(), nullable=True),
    sa.Column('todo_item_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['todo_item_id'], ['todo_item.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_item_tags')
    op.drop_table('tag')
    # ### end Alembic commands ###
