# Generated by Django 2.2.2 on 2019-07-08 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friendrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequests',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_received', to=settings.AUTH_USER_MODEL, verbose_name='receiver'),
        ),
    ]
