version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  app:
    image: registry.gitlab.propulsion-home.ch/raquel/droplet_dockerized_homework:master
    command: "sh /scripts/run_prod.sh"
    env_file: prod.env
    networks:
      - app-network

networks:
  app-network:
