version: "3"
services:

  app:
    image: registry.gitlab.propulsion-home.ch/raquel/week4day3_nginx_in_docker:latest
    ports:
      - "8000:80"

    volumes:
      - ./app:/usr/share/nginx/html
networks:
  app-network: