# Generated by Django 2.2.2 on 2019-06-17 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Default post title', max_length=200, null=True, verbose_name='my post title')),
                ('content', models.CharField(blank=True, default='Default post content', max_length=200, null=True, verbose_name='my post content')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='created')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='created')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Post', verbose_name='post likes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
