version: '3'
services:
  nginx:
    image: nginx:1.15.0
    ports:
      - "9000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network
      
  app:
    image: registry.gitlab.propulsion-home.ch/full-stack/solutions/flask-todo-nginx-gunicorn-in-docker:latest
    command: "sh /scripts/run.sh"
    environment:
      FLASK_APP: app.py
      FLASK_DEBUG: 0
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres:

networks:
  app-network:
