version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network

  postgres:
    image: postgres:latest
    env_file:
      - dev.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    image: registry.gitlab.propulsion-home.ch/raquel/droplet_dockerized:latest
    command: "sh /scripts/run.sh"
    env_file:
      - dev.env
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./app:/app

volumes:
  postgres:

# network for all the docker containers
#to interact between each other
networks:
  app-network: