version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "1234:80"
    networks:
      - app-network
    volumes:
      - ./nginx:/etc/nginx/conf.d
  app:
    image: registry.gitlab.propulsion-home.ch/ianstump/flask-livecoding:latest
    networks:
      - app-network
    command: "/opt/conda/envs/app/bin/gunicorn -w 4 -b 0.0.0.0:5000 app:app"
    environment:
      FLASK_DEBUG: 1
    volumes:
      - ./app:/app
networks:
  app-network: