version: "3"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 4777:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres: