version: '3'
services:
  app:
    image: registry.gitlab.propulsion-home.ch/raquel/django_docker:latest
    command: "sh /app/scripts/run.sh"
    env_file:
      - dev.env
    ports:
      - "8080:8000"
      - "2222:22"
    volumes:
      - ./app:/app
      - static-files:/static-files/
      - media-files:/media-files/
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config:/etc/nginx/conf.d
      - static-files:/static-files/
      - media-files:/media-files/

volumes:
  postgres:
  static-files:
  media-files:

